import { verticalScale } from "../utils/responsiblity";
import { SCREEN_HEIGHT } from "./sizes";

//SPLASH SCREEN
export const CIRCLE_INITIAL_ROTATION = 0;
export const CIRCLE_ICON_INITIAL_VISIBILITY = 1;
export const CIRCLE_INITIAL_TRANSLATION = 1;
export const CIRCLE_ROTATION_DURATION = 1000;
export const CIRCLE_ICON_VISIBILITY_DURATION = 100;
export const CIRCLE_TRANSLATION_DELAY = 500;
export const CIRCLE_TRANSLATION_DURATION = 700;

//PICKER
export const PICKER_ANIMATION_DELAY = 300;
export const PICKER_ANIMATION_DURATION = 300;
export const PICKER_START_Y_POSITION = 0;
export const PICKER_START_X_POSITION = 0;
export const PICKER_END_Y_POSITION = verticalScale(-60);

//FLOATING BUTTON
export const BUTTON_ANIMATION_DURATION = 300;
export const ADD_BUTTON_INITIAL_BOTTOM = 30;
export const DELETE_BUTTON_INITIAL_BOTTOM = 30;
export const ADD_BUTTON_FINAL_BOTTOM = 90;
export const DELETE_BUTTON_FINAL_BOTTOM = 170;

export const DELETE_BUTTON_ANIMATION_DELAY = 0;
export const ADD_BUTTON_ANIMATION_DELAY = 100;

export const FLOATING_CONTAINER_INITIAL_POSITION = 20;
export const FLOATING_CONTAINER_END_POSITION = -60;
export const FLOATING_CONTAINER_DURATION = 200;
export const FLOATING_CONTAINER_DELAY = 200;

//BOTTOM BAR
export const BOTTOM_BAR_INITIAL_POSITION = SCREEN_HEIGHT;
export const BOTTOM_BAR_END_POSITION_RIGHT = SCREEN_HEIGHT - verticalScale(100);
export const BOTTOM_BAR_POSITION_ANIMATION_DURATION = 200;

//LIST HEADER
export const HEADER_TITLE_END_POSITION = 0;
export const HEADER_TITLE_TRANSLATION_DURATION = 250;
export const HEADER_BUTTON_TRANSLATION_DURATION = 250;
export const HEADER_BUTTON_INITIAL_POSITION = 0;
